version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
  pre_build:
    commands:
      - docker-compose up -d
  build:
    commands:
      - mvn test
reports:
  Selenium:
    file-format: CucumberJson
    files:
      - target/json/output.json
